DROP SEQUENCE MEMBERNOSEQ;
DROP TABLE MYMEMBER;

CREATE SEQUENCE MEMBERNOSEQ;

CREATE TABLE MYMEMBER(
	MEMBERNO NUMBER PRIMARY KEY,
	MEMBERID VARCHAR2(100) NOT NULL,
	MEMBERPW VARCHAR2(100) NOT NULL,
	MEMBERNAME VARCHAR2(100) NOT NULL
);

INSERT INTO MYMEMBER VALUES(MEMBERNOSEQ.NEXTVAL, 'admin', 'admin1234', '관리자');

SELECT MEMBERNO, MEMBERID, MEMBERPW, MEMBERNAME FROM MYMEMBER;