DROP SEQUENCE BOARDSEQ;
DROP TABLE MYBOARD;

CREATE SEQUENCE BOARDSEQ;
CREATE TABLE MYBOARD(
	BOARDNO NUMBER PRIMARY KEY,
	BOARDNAME VARCHAR2(500) NOT NULL,
	BOARDTITLE VARCHAR2(1000) NOT NULL,
	BOARDCONTENT VARCHAR2(4000) NOT NULL,
	BOARDDATE DATE NOT NULL
);

INSERT INTO MYBOARD VALUES(BOARDSEQ.NEXTVAL, '작성자', '제목', '내용', SYSDATE);

SELECT * FROM MYBOARD;