DROP SEQUENCE MYMEMBERSEQ;
DROP TABLE MYMEMBER;

CREATE SEQUENCE MYMEMBERSEQ;
CREATE TABLE MYMEMBER(
	MEMBERNO NUMBER PRIMARY KEY,
	MEMBERID VARCHAR2(100) NOT NULL,
	MEMBERPW VARCHAR2(100) NOT NULL,
	MEMBERNAME VARCHAR2(100) NOT NULL
);

INSERT INTO MYMEMBER VALUES(MYMEMBERSEQ.NEXTVAL, 'admin', 'admin1234', '관리자');

SELECT * FROM MYMEMBER;