DROP SEQUENCE BOARDNOSEQ;
DROP TABLE MYBOARD;

CREATE SEQUENCE BOARDNOSEQ;
CREATE TABLE MYBOARD(
	BOARDNO NUMBER PRIMARY KEY,
	BOARDTITLE VARCHAR2(500) NOT NULL,
	BOARDNAME VARCHAR2(100) NOT NULL,
	BOARDCONTENT VARCHAR2(2000) NOT NULL,
	BOARDDATE DATE NOT NULL
);

INSERT INTO MYBOARD VALUES(BOARDNOSEQ.NEXTVAL, 'TITLE', 'WRITER', 'CONTENT', SYSDATE);

SELECT * FROM MYBOARD;