DROP SEQUENCE JDBCBOARDSEQ;
DROP TABLE JDBCBOARD;

CREATE SEQUENCE JDBCBOARDSEQ;

CREATE TABLE JDBCBOARD(
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(500) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL
);

INSERT INTO JDBCBOARD VALUES(JDBCBOARDSEQ.NEXTVAL, 'ADMIN', 'ADMIN TEST', 'ADMIN CONTENT', SYSDATE);

SELECT SEQ, WRITER, TITLE, CONTENT, REGDATE FROM JDBCBOARD ORDER BY SEQ DESC;